task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  matrix:
    - name: clang-format
      container:
        image: silkeh/clang:19
      test_script: uname -rms && apt-get update -y && apt-get install --no-install-recommends -y git && git ls-files -z '**/*.c' '**/*.h' | xargs -0 -- clang-format --dry-run --style=file --Werror
