task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  matrix:
    - name: macOS
      macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:sequoia
      environment:
        CFLAGS: -I/opt/homebrew/opt/openssl@3/include -I/opt/homebrew/include
        LDFLAGS: -L/opt/homebrew/opt/openssl@3/lib -L/opt/homebrew/lib
        PKG_CONFIG_PATH: /opt/homebrew/opt/openssl@3/lib/pkgconfig
      install_script: brew update && brew install json-c libscrypt openssl python3 && env PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip install pexpect pytest
      test_script: uname -sr && python3 --version && mkdir build && cd build && cmake .. && cmake --build . && cmake --build . -- check && sudo cmake --build . -- install

    - name: clang-format
      container:
        image: silkeh/clang:19
      test_script: uname -rms && apt-get update -y && apt-get install --no-install-recommends -y git && git ls-files -z '**/*.c' '**/*.h' | xargs -0 -- clang-format --dry-run --style=file --Werror
