task:

  matrix:
    - name: macOS, XCode 12.1, Homebrew
      osx_instance:
        image: catalina-xcode-12.1
      environment:
        CFLAGS: -I/usr/local/opt/openssl/include -I/usr/local/include -g
        LDFLAGS: -L/usr/local/opt/openssl/lib -L/usr/local/lib
        PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
      install_script: brew update && brew install cunit json-c openssl && sudo pip3 install pexpect && mkdir scrypt-build && cd scrypt-build && curl https://www.tarsnap.com/scrypt/scrypt-1.3.0.tgz -o scrypt-1.3.0.tgz && tar xf scrypt-1.3.0.tgz && cd scrypt-1.3.0 && ./configure --enable-libscrypt-kdf && make && sudo make install && cd ../..

  test_script: uname -sr && python3 --version && mkdir build && cd build && cmake .. && cmake --build . -- pw-cli pw-gui-test-stub pw-gui passwand-tests && ./passwand-tests && ../tests/integration-tests.py --verbose && sudo cmake --build . -- install
