language: c

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=
      - TARGETS=pw-cli
      - MATRIX_EVAL="CC=gcc-6"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui"
      - MATRIX_EVAL="CC=gcc-6"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui"
      - MATRIX_EVAL="CC=gcc-6"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=
      - TARGETS=pw-cli
      - MATRIX_EVAL="CC=clang"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui"
      - MATRIX_EVAL="CC=clang"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui"
      - MATRIX_EVAL="CC=clang"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcunit1-dev libjson-c-dev ${GTK}
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . -- ${TARGETS}
  - cmake --build . -- passwand-tests
  - cmake --build . -- test
  - cmake --build . -- install
