language: c

matrix:
  include:
  - name: Linux, GCC 5, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-5"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 5, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-5"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 5, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-5"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 6, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-6"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 6, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-6"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 6, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-6"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 7, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-7"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 7, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-7"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 7, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-7"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 8, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-8"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 8, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-8"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 8, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-8"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 6.0, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=clang-6.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 6.0, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-6.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 6.0, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-6.0"
      - CTEST_OUTPUT_ON_FAILURE=1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcunit1-dev libjson-c-dev python3-pexpect ${GTK}
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . -- ${TARGETS}
  - cmake --build . -- passwand-tests
  - cmake --build . -- test
  - cmake --build . -- install
