language: c

matrix:
  include:
  - name: Ubuntu Linux 18.04, GCC 5, no GTK
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-5
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-5"
  - name: Ubuntu Linux 18.04, GCC 5, GTK 2
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-5
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-5"
  - name: Ubuntu Linux 18.04, GCC 5, GTK 3
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-5
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-5"
  - name: Ubuntu Linux 18.04, GCC 6, no GTK
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-6"
  - name: Ubuntu Linux 18.04, GCC 6, GTK 2
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-6"
  - name: Ubuntu Linux 18.04, GCC 6, GTK 3
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-6"
  - name: Ubuntu Linux 18.04, GCC 7, no GTK
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-7
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-7"
  - name: Ubuntu Linux 18.04, GCC 7, GTK 2
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-7
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-7"
  - name: Ubuntu Linux 18.04, GCC 7, GTK 3
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-7
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-7"
  - name: Ubuntu Linux 18.04, GCC 8, no GTK
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-8
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-8"
  - name: Ubuntu Linux 18.04, GCC 8, GTK 2
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-8
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-8"
  - name: Ubuntu Linux 18.04, GCC 8, GTK 3
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - g++-8
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-8"
  - name: Ubuntu Linux 18.04, Clang 4.0, no GTK
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - clang-4.0
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=clang-4.0"
  - name: Ubuntu Linux 18.04, Clang 4.0, GTK 2
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - clang-4.0
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-4.0"
  - name: Ubuntu Linux 18.04, Clang 4.0, GTK 3
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - clang-4.0
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-4.0"
  - name: Ubuntu Linux 18.04, Clang 5.0, no GTK
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - clang-5.0
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=clang-5.0"
  - name: Ubuntu Linux 18.04, Clang 5.0, GTK 2
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - clang-5.0
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-5.0"
  - name: Ubuntu Linux 18.04, Clang 5.0, GTK 3
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - clang-5.0
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-5.0"
  - name: Ubuntu Linux 18.04, Clang 6.0, no GTK
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - clang-6.0
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=clang-6.0"
  - name: Ubuntu Linux 18.04, Clang 6.0, GTK 2
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - clang-6.0
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-6.0"
  - name: Ubuntu Linux 18.04, Clang 6.0, GTK 3
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - clang-6.0
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-6.0"

  - name: macOS, XCode 11.2 Clang
    os: osx
    osx_image: xcode11.2
    addons:
      homebrew:
        update: true
        packages:
          - cunit
          - openssl
    env:
      - CFLAGS="${CFLAGS} -I/usr/local/opt/openssl/include -I$(brew --prefix)/include"
      - LDFLAGS="${LDFLAGS} -L/usr/local/opt/openssl/lib -L$(brew --prefix)/lib"
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL=
      - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

  - name: macOS, XCode 11.3 Clang
    os: osx
    osx_image: xcode11.3
    addons:
      homebrew:
        update: true
        packages:
          - cunit
          - openssl
    env:
      - CFLAGS="${CFLAGS} -I/usr/local/opt/openssl/include -I$(brew --prefix)/include"
      - LDFLAGS="${LDFLAGS} -L/usr/local/opt/openssl/lib -L$(brew --prefix)/lib"
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL=
      - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx"   ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get install -y libcunit1-dev libjson-c-dev python3-pexpect ${GTK}; fi
  # No need to install json-c because it comes with XCode
  - if [ "${TRAVIS_OS_NAME}" = "osx"   ]; then pip3 install pexpect; fi
  - eval "${MATRIX_EVAL}"
  # build and install libscrypt-kdf
  - mkdir scrypt-build && cd scrypt-build && curl https://www.tarsnap.com/scrypt/scrypt-1.3.0.tgz -o scrypt-1.3.0.tgz && tar xf scrypt-1.3.0.tgz && cd scrypt-1.3.0 && ./configure --enable-libscrypt-kdf && make && sudo make install && cd ../..

script:
  - mkdir build && cd build && cmake .. && cmake --build . -- ${TARGETS} passwand-tests && ./passwand-tests && ../tests/integration-tests.py --verbose && sudo env "PATH=$PATH" cmake --build . -- install
