language: c

matrix:
  include:
  - name: Linux, GCC 5, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-5"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 5, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-5"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 5, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-5"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 6, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-6"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 6, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-6"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 6, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-6"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 7, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-7"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 7, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-7"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 7, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-7"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 8, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-8"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 8, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-8"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, GCC 8, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-8"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 3.8, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.8
        packages:
          - clang-3.8
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=clang-3.8"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 3.8, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.8
        packages:
          - clang-3.8
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-3.8"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 3.8, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.8
        packages:
          - clang-3.8
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-3.8"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 3.9, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.9
        packages:
          - clang-3.9
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=clang-3.9"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 3.9, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.9
        packages:
          - clang-3.9
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-3.9"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 3.9, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.9
        packages:
          - clang-3.9
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-3.9"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 4.0, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=clang-4.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 4.0, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-4.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 4.0, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-4.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 5.0, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=clang-5.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 5.0, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-5.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 5.0, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-5.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 6.0, no GTK
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - g++-6
    env:
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=clang-6.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 6.0, GTK 2
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - g++-6
    env:
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-6.0"
      - CTEST_OUTPUT_ON_FAILURE=1
  - name: Linux, Clang 6.0, GTK 3
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - g++-6
    env:
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=clang-6.0"
      - CTEST_OUTPUT_ON_FAILURE=1

  - name: macOS, XCode 9.4 Clang
    os: osx
    osx_image: xcode9.4
    env:
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL=
      - CTEST_OUTPUT_ON_FAILURE=1
      # Make OpenSSL findable
      - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

  - name: macOS, XCode 10.0 Clang
    os: osx
    osx_image: xcode10
    env:
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL=
      - CTEST_OUTPUT_ON_FAILURE=1
      - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

  - name: macOS, XCode 10.1 Clang
    os: osx
    osx_image: xcode10.1
    env:
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL=
      - CTEST_OUTPUT_ON_FAILURE=1
      - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

  - name: macOS, XCode 10.2 Clang
    os: osx
    osx_image: xcode10.2
    # XXX: Apple "helpfully" ships OpenSSL without headers after macOS 10.1. To
    # work around this, ask Homebrew to install a complete version with headers
    # and then redirect to it with env variables below.
    # See https://github.com/Tarsnap/scrypt/issues/20
    addons:
      homebrew:
        packages:
          - openssl
    env:
      - CFLAGS="${CFLAGS} -I/usr/local/opt/openssl/include -I$(brew --prefix)/include"
      - LDFLAGS="${LDFLAGS} -L/usr/local/opt/openssl/lib -L$(brew --prefix)/lib"
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL=
      - CTEST_OUTPUT_ON_FAILURE=1
      - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx"   ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get install -y libcunit1-dev libjson-c-dev python-pexpect ${GTK}; fi
  # No need to install json-c because it comes with XCode
  - if [ "${TRAVIS_OS_NAME}" = "osx"   ]; then brew install cunit; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx"   ]; then pip install pexpect; fi
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . -- ${TARGETS}
  - cmake --build . -- passwand-tests
  - cmake --build . -- test
  - cmake --build . -- install
