language: c

matrix:
  include:
  - name: Ubuntu Linux 20.04, GCC 7, no GTK
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-7
          # we need to install libscrypt-kdf1 explicitly
          # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962425
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -Werror"
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-7"
  - name: Ubuntu Linux 20.04, GCC 7, GTK 2
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-7
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      # XXX: we need to disable -Wdeprecated-declarations because the GTK 2
      # headers trigger this
      - CFLAGS="-g -Werror -Wno-deprecated-declarations"
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-7"
  - name: Ubuntu Linux 20.04, GCC 7, GTK 3
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-7
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -Werror"
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-7"
  - name: Ubuntu Linux 20.04, GCC 8, no GTK
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-8
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -Werror"
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-8"
  - name: Ubuntu Linux 20.04, GCC 8, GTK 2
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-8
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -Werror -Wno-deprecated-declarations"
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-8"
  - name: Ubuntu Linux 20.04, GCC 8, GTK 3
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-8
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -Werror"
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-8"
  - name: Ubuntu Linux 20.04, GCC 9, no GTK
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-9
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -Werror"
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-9"
  - name: Ubuntu Linux 20.04, GCC 9, GTK 2
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-9
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -Werror -Wno-deprecated-declarations"
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-9"
  - name: Ubuntu Linux 20.04, GCC 9, GTK 3
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-9
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -Werror"
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-9"
  - name: Ubuntu Linux 20.04, GCC 10, no GTK, ASan, UBSan
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-10
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -fsanitize=address,undefined -fno-sanitize-recover=address,undefined -Werror"
      - GTK=
      - TARGETS="pw-cli pw-gui-test-stub"
      - MATRIX_EVAL="CC=gcc-10"
      - UBSAN_OPTIONS=print_stacktrace=1
  - name: Ubuntu Linux 20.04, GCC 10, GTK 2, ASan, UBSan
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-10
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -fsanitize=address,undefined -fno-sanitize-recover=address,undefined -Werror -Wno-deprecated-declarations"
      - GTK=libgtk2.0-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-10"
      - UBSAN_OPTIONS=print_stacktrace=1
  - name: Ubuntu Linux 20.04, GCC 10, GTK 3, ASan, UBSan
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - gcc-10
          - libscrypt-kdf1
          - libscrypt-kdf-dev
          - pylint
    env:
      - CFLAGS="-g -fsanitize=address,undefined -fno-sanitize-recover=address,undefined -Werror"
      - GTK=libgtk-3-dev
      - TARGETS="pw-cli pw-gui-test-stub pw-gui"
      - MATRIX_EVAL="CC=gcc-10"
      - UBSAN_OPTIONS=print_stacktrace=1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcunit1-dev libjson-c-dev python3-pexpect ${GTK}
  - eval "${MATRIX_EVAL}"

script:
  - python3 -m pylint --errors-only ./tests/integration-tests.py && mkdir build && cd build && cmake .. && cmake --build . -- ${TARGETS} passwand-tests && ./passwand-tests && ../tests/integration-tests.py --verbose && sudo env "PATH=$PATH" cmake --build . -- install
